const fs = require('fs');
let js = fs.readFileSync('assets/index-ONzyNlzA.js', 'utf8');

// 1. Inject VersionBar_1mrd
const oeDef = "function VersionBar_1mrd(){let[e,t]=(0,l.useState)(()=>{let d=new Date();return d.toLocaleTimeString('de-DE',{hour:'2-digit',minute:'2-digit',second:'2-digit'})});(0,l.useEffect)(()=>{let iv=setInterval(()=>{let d=new Date();t(d.toLocaleTimeString('de-DE',{hour:'2-digit',minute:'2-digit',second:'2-digit'}))},1000);return()=>clearInterval(iv)},[]);let now=new Date();let dateStr=now.toLocaleDateString('de-DE',{weekday:'short',day:'2-digit',month:'2-digit',year:'numeric'});return(0,C.jsxs)('div',{className:'flex items-center justify-between px-1 py-1.5 mb-1 text-[10px] font-bold text-ink-muted uppercase tracking-wide border-b border-line/30',children:[(0,C.jsx)('span',{className:'text-pop-violet font-black tracking-widest',children:'v1.8.6.3'}),(0,C.jsx)('span',{className:'text-ink-muted/70',children:dateStr}),(0,C.jsx)('span',{className:'font-mono text-ink-muted tabular-nums',children:e})]})}"
js = js.replace('var ve=1e9;function ye({games:e', 'var ve=1e9;' + oeDef.replace(/'/g, '`') + 'function ye({games:e');

// 2. Fix layout and inject dynamic import buttons
const pattern2 = /\(0,C\.jsx\)\(`div`,{className:`h-full flex flex-col overflow-hidden`,children:\(0,C\.jsxs\)\(`div`,{className:`mx-auto flex w-full max-w-xl flex-col flex-1 min-h-0 gap-2 px-3 sm:px-4 pt-safe`,children:\[\(0,C\.jsxs\)\(`header`,{className:`flex items-center justify-between gap-2`.*?\)\}\)\}\)\}\)/s;

const newHTML = "(0,C.jsx)(`div`,{className:`w-full h-full flex-1 min-h-0 flex flex-col overflow-hidden`,children:(0,C.jsxs)(`div`,{className:`mx-auto flex w-full max-w-xl flex-col flex-1 min-h-0 gap-2 px-3 sm:px-4 pt-safe`,children:[(0,C.jsx)(VersionBar_1mrd,{}),(0,C.jsxs)(`header`,{className:`flex items-center justify-between gap-2 mb-2`,children:[(0,C.jsx)(be,{}),(0,C.jsx)(_e,{coins:i.coins})]}),(0,C.jsxs)(`div`,{className:`flex flex-wrap items-center gap-3 mb-4 shrink-0`,children:[(0,C.jsxs)(`button`,{type:`button`,onClick:()=>import('./daily-manager.js').then(m=>m.openDailyModal()),className:`flex items-center gap-2 rounded-2xl bg-gradient-to-br from-purple-500/20 to-fuchsia-500/10 py-2.5 px-4 font-black text-sm text-fuchsia-50 shadow-lg shadow-purple-900/20 active:scale-95 transition border border-purple-500/40 hover:border-purple-400 cursor-pointer`,children:[(0,C.jsx)(`span`,{className:`text-xl leading-none drop-shadow-md`,children:`\uD83C\uDF81`}),(0,C.jsx)(`span`,{className:`tracking-wide`,children:`Bonus`})]}),(0,C.jsxs)(`button`,{type:`button`,onClick:()=>import('./challenges-manager.js').then(m=>m.openChallengesModal()),className:`flex items-center gap-2 rounded-2xl bg-gradient-to-br from-amber-500/20 to-orange-500/10 py-2.5 px-4 font-black text-sm text-amber-50 shadow-lg shadow-amber-900/20 active:scale-95 transition border border-amber-500/40 hover:border-amber-400 cursor-pointer relative`,children:[(0,C.jsx)(`span`,{className:`text-xl leading-none drop-shadow-md`,children:`\uD83C\uDFAB`}),(0,C.jsx)(`span`,{className:`tracking-wide`,children:`Stempel`}),(0,C.jsx)(`span`,{className:`absolute -top-2 -right-2 rounded-lg bg-gradient-to-b from-amber-400 to-yellow-500 px-1.5 py-0.5 text-[10px] font-black text-bg shadow-md border border-yellow-200/50`,children:`+250`})]})]})]})})";

js = js.replace(pattern2, newHTML);

// 3. Bump version string in footer
js = js.replace(/var Qe=\{id:`v1\.8\.5`,commit:`[^`]+`,stamp:`[^`]+`\}/, 'var Qe={id:`v1.8.6.3`,commit:`d22caff`,stamp:`29.09.2026, 14:39`}');

fs.writeFileSync('assets/index-ONzyNlzA.js', js, 'utf8');
